preset: none

enabled:
  - concat_with_spaces
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_before_return
  - braces
  - class_definition
  - elseif
  - encoding
  - full_opening_tag
  - length_ordered_imports
  - method_argument_space
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_throw
  - no_multiline_whitespace_around_double_arrow
  - no_spaces_after_function_name
  - no_unused_imports
  - print_to_echo
  - whitespace_after_comma_in_array